### PR TITLE
linux-loader: Prepare v0.14.1 release

### PR DESCRIPTION
**Pull request by slp**
### Summary of the PR

Prepare v0.14.1 release.

### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [x] All commits in this PR have Signed-Off-By trailers (with
  `git commit -s`), and the commit message has max 60 characters for the
  summary and max 75 characters for each description line.
- [ ] All added/changed functionality has a corresponding unit/integration
  test.
- [ ] All added/changed public-facing functionality has entries in the "Upcoming 
  Release" section of CHANGELOG.md (if no such section exists, please create one).
- [ ] Any newly added `unsafe` code is properly documented.

### CODE REVIEW

**Comment by arctic-alpaca** [comment]
The change is breaking and should be a major version increase to follow SemVer. The removal of the `rawfd` feature on `vm-memory` removed implementations of `ReadVolatile` for `std::fs::File`, `std::net::TcpStream`, etc. from `linux-loader`. This means that code that compiles with `0.14.0` won't compile with `0.14.1`.

The following code compiles with 
```toml
[dependencies]
linux-loader = "0.14.0"
vm-memory = { version = "0.18.0", default-features = false, features = ["backend-mmap"] }
```
but does not compile with 
```toml
[dependencies]
linux-loader = { git = "https://github.com/rust-vmm/rust-vmm" }
vm-memory = { git = "https://github.com/rust-vmm/rust-vmm", default-features = false, features = ["backend-mmap"] }
```

```rust
use linux_loader::loader::{Elf, KernelLoader};
use std::fs::File;
use vm_memory::{GuestAddress, GuestMemoryMmap};

fn main() {
    let mem_size: usize = 0x1000000;
    let himem_start = GuestAddress(0x0);
    let kernel_addr = GuestAddress(0x200000);
    let gm = GuestMemoryMmap::<()>::from_ranges(&[(GuestAddress(0x0), mem_size)]).unwrap();
    let mut kernel_image = File::open("/dev/null").unwrap();
    Elf::load(&gm, Some(kernel_addr), &mut kernel_image, Some(himem_start)).unwrap();
}
```

```
error[E0277]: the trait bound `File: ReadVolatile` is not satisfied
   --> src/main.rs:11:39
    |
 11 |     Elf::load(&gm, Some(kernel_addr), &mut kernel_image, Some(himem_start)).unwrap();
    |     ---------                         ^^^^^^^^^^^^^^^^^ the trait `ReadVolatile` is not implemented for `File`
    |     |
    |     required by a bound introduced by this call
    |
help: the following other types implement trait `ReadVolatile`
   --> /home/julian/.cargo/git/checkouts/rust-vmm-eff3fcd574762e7b/5062d95/vm-memory/src/io.rs:318:1
    |
318 |   impl ReadVolatile for &[u8] {
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^ `&[u8]`
...
390 | / impl<T> ReadVolatile for Cursor<T>
391 | | where
392 | |     T: AsRef<[u8]>,
    | |___________________^ `std::io::Cursor<T>`
note: required by a bound in `linux_loader::loader::KernelLoader::load`
   --> /home/julian/.cargo/git/checkouts/rust-vmm-eff3fcd574762e7b/5062d95/linux-loader/src/loader/mod.rs:183:19
    |
176 |     fn load<F, M: GuestMemoryBackend>(
    |        ---- required by a bound in this associated function
...
183 |         F: Read + ReadVolatile + Seek;
    |                   ^^^^^^^^^^^^ required by this bound in `KernelLoader::load`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `release-test` (bin "release-test") due to 1 previous error
```

**Comment by slp** [comment]
On a second thought, without enabling `rawfd` in `vm-memory`, the `linux-loader` crate is barely usable. Let me revert the change instead.
